[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/screen-printing-myrtle-beach-sc.html"
  to = "/custom-tshirts-conway-sc.html"
  status = 301
  force = true

[[redirects]]
  from = "/screen-printing-myrtle-beach-sc.htm"
  to = "/custom-tshirts-conway-sc.html"
  status = 301
  force = true

[[redirects]]
  from = "/screen-printing-myrtle-beach-sc"
  to = "/custom-tshirts-conway-sc.html"
  status = 301
  force = true
