backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "store"
public_folder: "/store"

collections:
  - name: "store_products"
    label: "🛒 Store Products"
    files:
      - label: "Products"
        name: "products_file"
        file: "data/products.json"

        editor:
          preview: false

        fields:
          - label: "Product List"
            name: "products"
            widget: "list"
            summary: "{{fields.name}} (ID: {{fields.id}})"

            fields:
              - label: "Product ID (Unique)"
                name: "id"
                widget: "string"
                required: true
                hint: "Example: C101 or O105."

              - label: "Product Name"
                name: "name"
                widget: "string"
                required: true

              - label: "Category Tag"
                name: "category"
                widget: "select"
                options: ["Originals", "Fall", "Christmas", "LE"]
                required: true

              - label: "Apparel Types"
                name: "product_options"
                widget: "list"
                field:
                  label: "Type Name"
                  name: "type"
                  widget: "select"
                  options: ["Tee_Shirt", "Sweatshirt", "Hoodie", "Baseball_Tee"]

              - label: "Available Colors"
                name: "colors"
                widget: "list"
                field:
                  label: "Color Name"
                  name: "color"
                  widget: "string"
